### ISSUE TITLE
Can I create a fully FOSS fork of your app?

### ISSUE THREAD

**Issue by flexagoon** [nikolaDrljaca/text-recognition-app#2]
Would you like your app to be published on F-Droid? I can do that for you if you want to

**Comment by flexagoon** [comment]
Since your app uses MLKit and Google Translate, I wouldn't be able to add it to FDroid. Would you mind if I create a fork of your app which uses opensource libraries instead?

Your repository doesn't include a license, so I'm asking here

**Comment by flexagoon** [comment]
Just pinging you in case GitHub doesnt automatically notify you of new issues

@nikolaDrljaca @drljacao96

**Comment by nikolaDrljaca** [comment]
I have attached a license to the project. Seems that we missed that one when publishing it. 
This is an open source app, so yeah you can fork it and modify it to your liking, we only ask that if you decide to publish it anywhere you give attributions.

**Comment by JVariance** [comment]
@flexagoon what's the current state of this?

**Comment by flexagoon** [comment]
@JVariance I'm currently not planning to do this unfortunately. I also don't have enought knowledge about native Android development.
